### ISSUE TITLE
Readme File -- 11 July  use of  datatype: charachter  ---- misspelling?

### ISSUE THREAD

**Issue by d76d30dbl** [hsbadr/COVID-19#1]
In Readme file, there is a field type:  charachter   --- repeated throughout
Is this a miss-spelling of "character" or does it refer to a special to a specific character-set ?

**Comment by hsbadr** [comment]
Thanks for catching that! Yes, it means character column type. It's been [fixed](https://github.com/hsbadr/COVID-19/commit/55caf7845710155d430ae97e474fe1f82ee76b2a).
